FROM python:3.10.6-slim AS builder

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/

RUN apt-get update -y && apt-get install -y python3-pip
RUN pip3 install -r requirements.txt

RUN rm requirements.txt

COPY python /usr/src/app/
COPY scripts /usr/src/app/
